import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { GithubIcon } from "hugeicons-react";
import { Navigation } from "@/components/Navigation";

type Project = { slug: string; title: string; tagline: string; tags: string[]; problem: string; overview: string; features: string[]; howItWorks: string; stack: string[]; live?: string; github?: string; impact: string; challenges?: string[]; future: string[]; img: string };

const PROJECTS: Record<string, Project> = {
  lynktern: { slug: "lynktern", title: "lynktern", tagline: "ai-assisted siwes platform for nigerian students", tags: ["ai", "saas", "education"], problem: "students in nigeria often manage siwes logbooks, reports, and internship tracking manually. the process is repetitive, difficult to validate, and spread across disconnected tools.", overview: "lynktern digitizes the siwes workflow with structured logs, ai assistance, placement matching, and reporting in one system.", features: ["ai-assisted logbook writing and validation", "internship matching", "automated report generation", "progress tracking dashboard", "supervisor review and feedback"], howItWorks: "students record activities in structured weekly logs. ai helps refine entries, progress is stored centrally, and reports are generated from the recorded work. supervisors can review activity through a dashboard.", stack: ["react", "typescript", "next.js", "tailwind css", "postgresql", "openai api"], live: "https://lynktern.pro", impact: "in development — core workflows for student logging, reporting, and progress tracking are in place.", challenges: ["keeping ai-generated entries structured and useful", "designing a workflow students can maintain weekly", "keeping log and report data consistent"], future: ["stronger internship recommendations", "student performance analytics", "richer supervisor feedback workflows"], img: "/shot-lynktern.png" },
  aesthura: { slug: "aesthura", title: "aesthura", tagline: "interior design portfolio and booking platform", tags: ["portfolio", "client-work", "design-system"], problem: "interior designers often rely on scattered platforms like instagram or whatsapp to showcase their work and manage clients. there is no structured system to present projects or handle bookings professionally.", overview: "aesthura is a digital platform for an interior design business to showcase completed work and let clients book services directly. it combines a clean portfolio experience with a simple booking system.", features: ["project showcase gallery", "service presentation", "client booking system", "structured portfolio layout", "responsive design for mobile and desktop"], howItWorks: "visitors explore completed interior projects, view design styles and services, select a service, then submit a booking request through the platform.", stack: ["next.js", "tailwind css", "frontend-focused architecture"], impact: "provides a professional digital presence for the business and replaces informal client communication with a structured booking flow.", challenges: ["designing a layout that highlights visual work effectively", "keeping the interface minimal while still informative", "building a simple but functional booking flow"], future: ["calendar-based booking system", "admin dashboard for managing clients", "client communication integration"], img: "/shot-aesthura.png" },
  shipixa: { slug: "shipixa", title: "shipixa", tagline: "shipping and logistics operations in one workspace", tags: ["logistics", "saas", "operations"], problem: "small businesses lose time switching between carriers, shipment updates, labels, and customer messages. fragmented tools make delivery operations difficult to track.", overview: "shipixa brings shipment management, carrier integrations, labels, and delivery updates into one operational view.", features: ["multi-carrier integration", "real-time shipment tracking", "automated label generation", "delivery analytics dashboard", "customer notifications"], howItWorks: "businesses manage shipments from a central workspace. carrier events update shipment status, while delivery data feeds notifications and operational reporting.", stack: ["node.js", "express", "react", "mongodb", "stripe api"], impact: "a single workflow for managing repetitive small-business shipping operations.", challenges: ["normalising carrier status updates", "keeping shipment data timely", "making operational data readable at a glance"], future: ["more carrier connections", "exception-handling alerts", "deeper delivery cost analytics"], img: "/shot-shipixa.jpg" },
  "classiq-store": { slug: "classiq-store", title: "classiq store", tagline: "a considered e-commerce experience for timeless fashion", tags: ["e-commerce", "retail", "web"], problem: "fashion shoppers need a clear way to discover products, complete purchases, and manage orders without a cluttered storefront.", overview: "classiq combines a focused fashion storefront with product discovery, checkout, and operational tools for managing orders and inventory.", features: ["filterable product catalogue", "cart and checkout", "stripe payment integration", "order management", "customer accounts and wishlists"], howItWorks: "products are organised into a browsable catalogue. shoppers filter, save, and purchase items, while order and inventory workflows support the store behind the scenes.", stack: ["next.js", "typescript", "prisma", "stripe", "vercel"], impact: "a complete foundation for a fashion store that keeps the shopping journey simple.", future: ["inventory alerts", "personalised discovery", "post-purchase communication"], img: "/shot-classiq.png" },
  nxlstchz: { slug: "nxlstchz", title: "nxlstchz", tagline: "digital brand platform for crocheted fashion", tags: ["brand", "fashion", "frontend"], problem: "small fashion brands often lack a strong digital presence and rely heavily on social media, limiting how they present products and build identity.", overview: "nxlstchz is a brand-focused website that establishes a strong identity for a crocheted-wear brand. it is both a visual brand statement and a platform to showcase products.", features: ["brand identity showcase", "product display system", "minimal fashion layout", "visual storytelling", "mobile-first experience"], howItWorks: "users land on the site, experience the brand visually, browse available pieces, and explore the style and identity of the brand.", stack: ["next.js", "tailwind css", "design-driven frontend"], impact: "creates a strong digital identity for the brand and provides a foundation for future commerce integration.", challenges: ["building a distinct visual identity", "balancing minimal design with product clarity", "ensuring the brand feels premium and cohesive"], future: ["full e-commerce functionality", "product ordering system", "inventory and catalog management"], img: "/shot-nxlstchz.png" },
};

export const Route = createFileRoute("/work/$projectId")({ head: ({ params }) => { const p = PROJECTS[params.projectId]; return { meta: [{ title: `${p?.title || "project"} — lambert.` }, { name: "description", content: p?.tagline || "Project case study" }] }; }, component: ProjectPage });

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border-t border-white/10 py-12 sm:py-16"><h2 className="mb-6 text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground">{title}</h2>{children}</section>; }

function ProjectPage() {
  const { projectId } = Route.useParams(); const p = PROJECTS[projectId];
  if (!p) return <div className="flex min-h-screen items-center justify-center bg-background"><div className="text-center"><h1 className="mb-4 text-4xl font-bold">project not found</h1><Link to="/work" className="text-muted-foreground hover:text-foreground">← back to work</Link></div></div>;
  return <div className="min-h-screen bg-background"><Navigation /><main className="mx-auto max-w-4xl px-5 py-24 sm:px-8"><Link to="/work" className="mb-16 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />back to work</Link>
    <header className="mb-20"><p className="mb-4 text-eyebrow">case study · {p.slug}</p><h1 className="text-5xl font-extrabold tracking-tight sm:text-6xl">{p.title}</h1><p className="mt-5 max-w-2xl text-xl text-muted-foreground">{p.tagline}</p><div className="mt-7 flex flex-wrap gap-2">{p.tags.map((tag) => <span key={tag} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-muted-foreground">{tag}</span>)}</div><div className="mt-8 flex flex-wrap gap-3">{p.live && <a href={p.live} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-foreground px-4 py-2.5 text-sm text-background hover:opacity-90"><ExternalLink className="h-4 w-4" />view live</a>}{p.github && <a href={p.github} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2.5 text-sm hover:bg-muted"><GithubIcon className="h-4 w-4" />github</a>}</div></header>
    <div className="mb-4 aspect-[16/9] overflow-hidden rounded-2xl border border-white/10 bg-muted"><img src={p.img} alt={`${p.title} preview`} className="h-full w-full object-cover grayscale" /></div>
    <Section title="problem"><p className="max-w-3xl text-lg leading-relaxed text-foreground/90">{p.problem}</p></Section><Section title="overview"><p className="max-w-3xl text-lg leading-relaxed text-foreground/90">{p.overview}</p></Section><Section title="what it does"><ul className="grid gap-3 sm:grid-cols-2">{p.features.map((x) => <li key={x} className="rounded-lg border border-white/10 px-4 py-4 text-sm text-foreground/90">— {x}</li>)}</ul></Section><Section title="how it works"><p className="max-w-3xl text-lg leading-relaxed text-foreground/90">{p.howItWorks}</p></Section><Section title="tech stack"><div className="flex flex-wrap gap-2">{p.stack.map((x) => <span key={x} className="rounded-full bg-secondary px-3 py-2 text-sm">{x}</span>)}</div></Section><Section title="links"><div className="space-y-3 text-sm">{p.live && <p>live: <a className="underline underline-offset-4" href={p.live} target="_blank" rel="noopener noreferrer">{p.live}</a></p>}{p.github && <p>github: <a className="underline underline-offset-4" href={p.github} target="_blank" rel="noopener noreferrer">{p.github}</a></p>}{!p.live && !p.github && <p className="text-muted-foreground">public links are not available for this project.</p>}</div></Section><Section title="impact / status"><p className="text-lg leading-relaxed text-foreground/90">{p.impact}</p></Section>{p.challenges && <Section title="challenges"><ul className="space-y-3 text-foreground/90">{p.challenges.map((x) => <li key={x}>— {x}</li>)}</ul></Section>}<Section title="future improvements"><ul className="space-y-3 text-foreground/90">{p.future.map((x) => <li key={x}>— {x}</li>)}</ul></Section>
  </main></div>;
}
